# Generated by Django 3.0.4 on 2021-10-01 02:50

from django.db import migrations, models
import django.db.models.deletion
import entrysheet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastUpdateDT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='SetList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField()),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(blank=True, max_length=32)),
                ('link', models.URLField(blank=True)),
                ('bass', models.ForeignKey(default=entrysheet.models.get_or_create_default_member1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='setlist_bass', to='entrysheet.Member')),
                ('drum', models.ForeignKey(default=entrysheet.models.get_or_create_default_member1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='setlist_drum', to='entrysheet.Member')),
                ('guitar1', models.ForeignKey(default=entrysheet.models.get_or_create_default_member1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='setlist_guitar1', to='entrysheet.Member')),
                ('guitar2', models.ForeignKey(default=entrysheet.models.get_or_create_default_member1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='setlist_guitar2', to='entrysheet.Member')),
                ('keyboard', models.ForeignKey(default=entrysheet.models.get_or_create_default_member1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='setlist_keyboard', to='entrysheet.Member')),
                ('other1', models.ForeignKey(default=entrysheet.models.get_or_create_default_member2, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='setlist_other1', to='entrysheet.Member')),
                ('other2', models.ForeignKey(default=entrysheet.models.get_or_create_default_member2, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='setlist_other2', to='entrysheet.Member')),
                ('vocal', models.ForeignKey(default=entrysheet.models.get_or_create_default_member1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='setlist_vocal', to='entrysheet.Member')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
    ]
